import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, Check, Menu, Moon, Star, Sun } from 'lucide-react';
import { benefits, faq, modules, problems, reviews, stats, steps, tariffs, trust } from './data/content';
import { Counter } from './components/Counter';
import { LeadForm } from './components/LeadForm';
import { initAnalytics } from './utils/analytics';

const fade = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-80px' } };
const go = (id: string) => document.querySelector(id)?.scrollIntoView({ behavior: 'smooth' });

function CareerIllustration() {
  return <motion.div initial={{ opacity: 0, scale: .92 }} animate={{ opacity: 1, scale: 1 }} className="relative mx-auto aspect-square max-w-lg rounded-[2.5rem] bg-gradient-to-br from-indigo-100 via-white to-cyan-100 p-6 shadow-soft dark:from-indigo-950 dark:via-slate-900 dark:to-cyan-950">
    <div className="absolute inset-8 rounded-[2rem] border border-white/70 dark:border-white/10" />
    <motion.div className="absolute left-10 top-16 rounded-3xl bg-white p-4 shadow-xl dark:bg-slate-800" animate={{ y: [0, -14, 0] }} transition={{ repeat: Infinity, duration: 5 }}><Star className="text-amber-400" /><b>Таланты</b></motion.div>
    <motion.div className="absolute bottom-14 right-10 rounded-3xl bg-slate-950 p-5 text-white shadow-xl dark:bg-white dark:text-slate-950" animate={{ y: [0, 12, 0] }} transition={{ repeat: Infinity, duration: 6 }}><b>Карьерный план</b><p className="text-sm opacity-75">на 6 месяцев</p></motion.div>
    <svg viewBox="0 0 360 360" className="h-full w-full"><defs><linearGradient id="g" x1="0" x2="1"><stop stopColor="#4f46e5"/><stop offset="1" stopColor="#06b6d4"/></linearGradient></defs><path d="M70 260 C130 240 135 185 180 172 S240 126 292 82" fill="none" stroke="url(#g)" strokeWidth="18" strokeLinecap="round"/><circle cx="70" cy="260" r="28" fill="#fff"/><circle cx="180" cy="172" r="34" fill="#fff"/><circle cx="292" cy="82" r="40" fill="#fff"/><path d="M269 83h47m-24-24v47" stroke="#4f46e5" strokeWidth="12" strokeLinecap="round"/></svg>
  </motion.div>;
}

export default function App() {
  const [dark, setDark] = useState(false); const [open, setOpen] = useState<number | null>(0);
  useEffect(() => { initAnalytics(); }, []);
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); }, [dark]);
  return <div className="min-h-screen bg-slate-50 text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100">
    <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/80 backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/80"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><button onClick={()=>go('#top')} className="text-2xl font-black tracking-tight">Prof<span className="text-indigo-600">.</span></button><div className="hidden gap-6 text-sm font-medium md:flex"><button onClick={()=>go('#program')}>Программа</button><button onClick={()=>go('#reviews')}>Отзывы</button><button onClick={()=>go('#tariffs')}>Тарифы</button><button onClick={()=>go('#faq')}>FAQ</button></div><div className="flex gap-2"><button aria-label="Тема" onClick={()=>setDark(!dark)} className="rounded-full border p-3 dark:border-white/10">{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><button onClick={()=>go('#consult')} className="hidden rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white dark:bg-white dark:text-slate-950 sm:block">Консультация</button><Menu className="md:hidden" /></div></nav></header>
    <main id="top"><section className="relative overflow-hidden px-4 py-20 sm:py-28"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_10%,rgba(99,102,241,.18),transparent_30%),radial-gradient(circle_at_80%_0%,rgba(6,182,212,.16),transparent_35%)]"/><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><motion.div {...fade}><span className="rounded-full bg-indigo-50 px-4 py-2 text-sm font-semibold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-200">Онлайн-профориентация с экспертами</span><h1 className="mt-6 text-5xl font-black leading-tight tracking-tight sm:text-6xl">Найдите профессию, которая подходит именно вам</h1><p className="mt-6 text-xl text-slate-600 dark:text-slate-300">Курс помогает подросткам, студентам и взрослым определить сильные стороны, выбрать карьерное направление и получить понятный план развития.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><button onClick={()=>go('#consult')} className="rounded-full bg-gradient-to-r from-indigo-600 to-cyan-500 px-7 py-4 font-bold text-white shadow-lg shadow-indigo-500/25 transition hover:scale-105">Пройти бесплатную консультацию</button><button onClick={()=>go('#program')} className="rounded-full border border-slate-300 px-7 py-4 font-bold transition hover:bg-white dark:border-white/15 dark:hover:bg-white/10">Посмотреть программу</button></div><div className="mt-10 grid grid-cols-4 gap-3">{trust.map((Icon,i)=><div key={i} className="rounded-2xl bg-white p-4 shadow-sm dark:bg-slate-900"><Icon className="mx-auto text-indigo-600 dark:text-cyan-300" /></div>)}</div></motion.div><CareerIllustration /></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-5 md:grid-cols-4">{problems.map(([t,d])=><motion.div {...fade} key={t} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-2 hover:shadow-soft dark:border-white/10 dark:bg-slate-900"><h3 className="text-xl font-bold">{t}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">{d}</p></motion.div>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-4xl font-black">Почему курс работает</h2><div className="mt-8 grid gap-5 md:grid-cols-3 lg:grid-cols-5">{benefits.map(({icon:Icon,title,text})=><motion.div {...fade} key={title} className="rounded-3xl bg-white p-6 shadow-soft dark:bg-slate-900"><Icon className="text-indigo-600 dark:text-cyan-300"/><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{text}</p></motion.div>)}</div></section>
    <section className="bg-white py-16 dark:bg-slate-900/40"><div className="mx-auto max-w-7xl px-4"><h2 className="text-4xl font-black">Как проходит обучение</h2><div className="mt-10 grid gap-6 md:grid-cols-4">{steps.map((s,i)=><motion.div {...fade} key={s} className="relative rounded-3xl bg-slate-50 p-6 dark:bg-slate-900"><span className="text-5xl font-black text-indigo-100 dark:text-indigo-900">0{i+1}</span><h3 className="mt-4 text-xl font-bold">{s}</h3><p className="mt-2 text-slate-600 dark:text-slate-300">Фиксируем выводы и следующий шаг, чтобы решение было осознанным.</p></motion.div>)}</div></div></section>
    <section id="program" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-4xl font-black">Программа курса</h2><div className="mt-8 grid gap-4">{modules.map((m,i)=><motion.div {...fade} key={m} className="flex items-center gap-5 rounded-3xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900"><span className="grid size-12 place-items-center rounded-2xl bg-indigo-600 font-bold text-white">{i+1}</span><b>{m}</b><ArrowRight className="ml-auto text-slate-400"/></motion.div>)}</div></section>
    <section id="reviews" className="overflow-hidden py-16"><div className="mx-auto max-w-7xl px-4"><h2 className="text-4xl font-black">Отзывы выпускников</h2><div className="mt-8 flex gap-5 overflow-x-auto pb-6 snap-x">{reviews.map(([name,text,img])=><article key={name} className="min-w-[310px] snap-center rounded-3xl bg-white p-6 shadow-soft dark:bg-slate-900"><img src={img} alt={name} loading="lazy" className="size-16 rounded-full object-cover"/><div className="mt-4 flex text-amber-400">{Array.from({length:5}).map((_,i)=><Star key={i} size={18} fill="currentColor" />)}</div><p className="mt-4 text-slate-600 dark:text-slate-300">“{text}”</p><b className="mt-5 block">{name}</b></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-5 md:grid-cols-3">{stats.map(([v,l])=><Counter key={v} value={v} label={l}/>)}</div></section>
    <section id="tariffs" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-4xl font-black">Тарифы</h2><div className="mt-8 grid gap-6 lg:grid-cols-3">{tariffs.map(({name,price,features,icon:Icon,popular})=><motion.div {...fade} key={name} className={`relative rounded-[2rem] border p-7 shadow-soft ${popular?'border-indigo-500 bg-indigo-600 text-white':'border-slate-200 bg-white dark:border-white/10 dark:bg-slate-900'}`}>{popular&&<span className="absolute -top-4 rounded-full bg-cyan-300 px-4 py-2 text-sm font-bold text-slate-950">Популярный</span>}<Icon/><h3 className="mt-5 text-2xl font-black">{name}</h3><p className="mt-3 text-4xl font-black">{price}</p><ul className="mt-6 space-y-3">{features.map(f=><li key={f} className="flex gap-3"><Check className="shrink-0"/> {f}</li>)}</ul><button onClick={()=>go('#consult')} className={`mt-8 w-full rounded-2xl px-5 py-4 font-bold ${popular?'bg-white text-indigo-700':'bg-slate-950 text-white dark:bg-white dark:text-slate-950'}`}>Купить курс</button></motion.div>)}</div></section>
    <section id="faq" className="mx-auto max-w-4xl px-4 py-16"><h2 className="text-4xl font-black">FAQ</h2><div className="mt-8 space-y-3">{faq.map(([q,a],i)=><div key={q} className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><button onClick={()=>setOpen(open===i?null:i)} className="flex w-full justify-between text-left text-lg font-bold"><span>{q}</span><span>+</span></button>{open===i&&<p className="mt-3 text-slate-600 dark:text-slate-300">{a}</p>}</div>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-4 py-20 lg:grid-cols-2"><div className="rounded-[2.5rem] bg-gradient-to-br from-indigo-600 to-cyan-500 p-10 text-white shadow-soft"><h2 className="text-4xl font-black">Сделайте первый шаг к профессии мечты уже сегодня</h2><p className="mt-5 text-lg text-white/85">Оставьте заявку — мы разберем ситуацию, цели и подскажем оптимальный маршрут.</p></div><LeadForm /></section></main><footer className="border-t border-slate-200 px-4 py-10 text-center text-sm text-slate-500 dark:border-white/10">© 2026 Prof. Онлайн-профориентация для осознанного выбора.</footer>
  </div>;
}
